[package]
name = "rusty-journal"
version = "0.1.0"
edition = "2024"

[dependencies]

structopt = "0.3"
serde_json= "1.0"


[dependencies.serde]
version= "1.0"
features= ["derive"]

[dependencies.chrono]
version ="0.4"
features= ["serde"]